# Makefile for div15_test.cpp
div15_test: div15_test.cpp div15.cpp div15.h
	g++ -Wall -O2 -o div15_test div15_test.cpp div15.cpp
div15_test.o: div15_test.cpp
	g++ -c div15_test.cpp
div15.o: div15.o
	g++ -c div15.cpp
div15_test.o: div15.h